// Generated by Selenium IDE

using System.Collections.Generic;
using NUnit.Framework;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;

namespace Selenium_Testing
{

    [TestFixture]
    public class TestnakovcomsearchQATest
    {
        private IWebDriver driver;
        public IDictionary<string, object> vars { get; private set; }
        private IJavaScriptExecutor js;

        [SetUp]
        public void SetUp()
        {
            driver = new ChromeDriver();
            js = (IJavaScriptExecutor) driver;
            vars = new Dictionary<string, object>();
        }

        [TearDown]
        protected void TearDown()
        {
            driver.Quit();
        }

        [Test]
        public void _01_Test_NakovCom_SearchQA()
        {
            driver.Navigate().GoToUrl("https://nakov.com/");
            driver.Manage().Window.Size = new System.Drawing.Size(1406, 1040);
            driver.FindElement(By.CssSelector("#sh > .smoothScroll")).Click();
            driver.FindElement(By.Id("s")).Click();
            driver.FindElement(By.Id("s")).SendKeys("QA");
            driver.FindElement(By.Id("s")).SendKeys(Keys.Enter);
            driver.FindElement(By.CssSelector(".entry-title")).Click();
            Assert.That(driver.FindElement(By.CssSelector(".entry-title")).Text,
                Is.EqualTo("Search Results for – \"QA\""));
        }
    }
}
